
name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: Start VM
      id: vm
      uses: vmactions/freebsd-vm@v1.3.4
      with:
        sync: zfs
    - name: Custom shell step 1
      shell: freebsd {0}
      run: |
        cd $GITHUB_WORKSPACE;
        pwd
    - name: Custom shell step 2
      run: |
        cd $GITHUB_WORKSPACE;
        sudo apt install tar gzip -y
        mkdir out
        pwd
        ls
        touch ./out/test
        mkdir upload
        tar -czvf free.tar.gz out/
        echo pwd
        pwd
        echo ls
        ls
        mv free.tar.gz upload

    - name: Build SuperTux
      shell: freebsd {0}
      run: |
        pwd
        pkg install -y git cmake googletest sdl2 sdl2_image openal-soft glew curl libogg libvorbis freetype2 libraqm glm physfs libfmt fribidi harfbuzz libraqm
        cd $GITHUB_WORKSPACE;
        pwd
        git clone --recursive https://github.com/1111Windows/supertux
        cd supertux
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=OFF -DINSTALL_SUBDIR_SHARE=share/supertux2 -DCMAKE_INSTALL_MESSAGE=NEVER -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_SUBDIR_BIN=bin -DENABLE_DISCORD=ON
        ls
        make -j4 VERBOSE=1
        mkdir out
        make install DESTDIR="./out" VERBOSE=1
        cd out/usr
        echo -e '#!/bin/sh\n' './bin/supertux2' >> run.sh
        chmod +x run.sh
        tar -czvf supertux.tar.gz ./
        cd ../../
        mkdir upload
        mv out/usr/supertux.tar.gz upload/

    - name: Upload tar archives
      uses: actions/upload-artifact@v4
      with:
          name: "-amd64-e-tgz"
          path: ./upload/*.tar.gz
          if-no-files-found: ignore
